# Generated by Django 5.1.7 on 2025-03-26 07:22

import django.utils.timezone
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_address', models.CharField(max_length=255)),
                ('field_area', models.FloatField()),
                ('crop_name', models.CharField(max_length=100)),
                ('farm_startdate', models.DateField(default=django.utils.timezone.now)),
                ('geometry', jsonfield.fields.JSONField()),
            ],
        ),
    ]
