# Generated by Django 5.1.7 on 2025-04-04 15:25

import django.utils.timezone
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_address', models.CharField(max_length=255)),
                ('field_area', models.FloatField()),
                ('crop_name', models.CharField(max_length=100)),
                ('farm_startdate', models.DateField(default=django.utils.timezone.now)),
                ('geometry', jsonfield.fields.JSONField()),
            ],
            options={
                'db_table': 'field_info',
            },
        ),
    ]
