# Generated by Django 5.1.7 on 2025-04-13 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmanage', '0002_field_description_field_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='farm_startdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
