# Generated by Django 5.1.7 on 2025-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmanage', '0002_field_description_field_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='farm_startdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
