# Generated by Django 5.1.7 on 2025-05-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldmanage', '0003_alter_field_farm_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyKeyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('keywords', models.JSONField()),
                ('field_id', models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.CASCADE, to='fieldmanage.field')),
            ],
            options={
                'db_table': 'monthly_keyword',
                'unique_together': {('field_id', 'year', 'month')},
            },
        ),
    ]
