version: '3.3'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: yourdb
  #     POSTGRES_USER: youruser
  #     POSTGRES_PASSWORD: yourpassword
