# Generated by Django 5.1.7 on 2025-05-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fieldmanage', '0004_monthlykeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPic',
            fields=[
                ('field_pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_name', models.CharField(max_length=255)),
                ('pic_path', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('pic_time', models.DateTimeField(null=True)),
                ('has_pest', models.BooleanField(null=True)),
                ('has_bug', models.BooleanField(null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fieldmanage.field')),
            ],
            options={
                'db_table': 'photoapp_fieldpic',
            },
        ),
    ]
