# Generated by Django 5.1.7 on 2025-05-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldpic',
            old_name='has_bug',
            new_name='has_disease',
        ),
    ]
