# Generated by Django 5.1.7 on 2025-05-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_rename_has_bug_fieldpic_has_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldpic',
            name='has_disease',
        ),
        migrations.RemoveField(
            model_name='fieldpic',
            name='has_pest',
        ),
        migrations.CreateModel(
            name='DiseaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('field_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_results', to='photoapp.fieldpic')),
            ],
            options={
                'db_table': 'disease_result',
            },
        ),
        migrations.CreateModel(
            name='PestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('field_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_results', to='photoapp.fieldpic')),
            ],
            options={
                'db_table': 'pest_result',
            },
        ),
    ]
