# Generated by Django 5.1.7 on 2025-05-18 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('drone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drone',
            },
        ),
        migrations.CreateModel(
            name='DroneErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronemanage.drone')),
            ],
            options={
                'db_table': 'drone_error_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DroneLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.IntegerField(default=0)),
                ('battery', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('gps_strength', models.IntegerField(default=0)),
                ('flight_mode', models.CharField(default='UNKNOWN', max_length=50)),
                ('flight_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronemanage.drone')),
            ],
            options={
                'db_table': 'drone_log',
            },
        ),
    ]
