# Generated by Django 5.1.7 on 2025-05-16 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.IntegerField(default=0)),
                ('drone_id', models.IntegerField(default=0)),
                ('battery', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('gps_strength', models.IntegerField(default=0)),
                ('flight_mode', models.CharField(default='UNKNOWN', max_length=50)),
                ('flight_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drone_log',
            },
        ),
    ]
