# Generated by Django 5.1.7 on 2025-05-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronemanage', '0003_alter_drone_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
