# Generated by Django 5.1.7 on 2025-04-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fieldmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTodo',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_content', models.TextField(blank=True, null=True)),
                ('cycle', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('is_tmp', models.BooleanField(default=False)),
                ('field', models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.CASCADE, to='fieldmanage.field')),
            ],
            options={
                'db_table': 'field_todo',
            },
        ),
    ]
