# Generated by Django 5.1.7 on 2025-04-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_fieldtodo_owner_alter_fieldtodo_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtodo',
            old_name='is_tmp',
            new_name='is_pest',
        ),
    ]
