# Generated by Django 5.1.7 on 2025-05-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_rename_is_tmp_fieldtodo_is_pest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('done', '완료'), ('skip', '미수행')], default='done', max_length=10)),
                ('task_id', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='todolist.fieldtodo')),
            ],
            options={
                'db_table': 'task_progress',
                'unique_together': {('task_id', 'date')},
            },
        ),
    ]
