# Generated by Django 5.1.7 on 2025-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_taskprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtodo',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
