# Generated by Django 5.1.7 on 2025-05-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_taskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtodo',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='fieldtodo',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
