# Generated by Django 5.1.7 on 2025-04-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPic',
            fields=[
                ('field_pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.IntegerField()),
                ('pic_name', models.CharField(max_length=255)),
                ('pic_path', models.ImageField(upload_to='field/')),
                ('pic_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropPic',
            fields=[
                ('crop_pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_name', models.CharField(max_length=255)),
                ('pic_path', models.ImageField(upload_to='crop/')),
                ('pic_time', models.DateTimeField(auto_now_add=True)),
                ('field_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipart_picture.fieldpic')),
            ],
        ),
        migrations.CreateModel(
            name='PestPic',
            fields=[
                ('pest_pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_name', models.CharField(max_length=255)),
                ('pic_path', models.ImageField(upload_to='pest/')),
                ('pic_time', models.DateTimeField(auto_now_add=True)),
                ('crop_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipart_picture.croppic')),
            ],
        ),
    ]
