# Generated by Django 5.1.7 on 2025-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipart_picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldpic',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldpic',
            name='log_file',
            field=models.FileField(null=True, upload_to='logs/'),
        ),
        migrations.AddField(
            model_name='fieldpic',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
