# Generated by Django 5.1.7 on 2025-05-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipart_picture', '0002_fieldpic_latitude_fieldpic_log_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestpic',
            name='crop_pic',
        ),
        migrations.DeleteModel(
            name='CropPic',
        ),
        migrations.DeleteModel(
            name='PestPic',
        ),
    ]
