# Generated by Django 5.1.7 on 2025-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('weather', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_info',
                'unique_together': {('region_name', 'date')},
            },
        ),
    ]
