# Generated by Django 5.1.7 on 2025-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='temperature',
            new_name='temperature_avg',
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.CharField(default='정보없음', max_length=50),
        ),
        migrations.AlterModelTable(
            name='weather',
            table='mid_weather',
        ),
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('weather', models.CharField(max_length=30)),
                ('precipitation', models.FloatField()),
                ('hour', models.IntegerField()),
            ],
            options={
                'db_table': 'hourly_weather',
                'unique_together': {('region_name', 'date', 'hour')},
            },
        ),
    ]
