# Generated by Django 5.1.7 on 2025-05-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_temperature_weather_temperature_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='temperature_max',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature_min',
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='precipitation',
            field=models.FloatField(default=0.0),
        ),
    ]
