# Generated by Django 5.1.7 on 2025-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_weather_temperature_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
